views.py
from flask import Blueprint, render_template, request
from werkzeug.wrappers.response import Response
import json
from utils import UtilsJSONEncoder
from models import ModelRequestObj, DataObj
from forecast.models.container import Container

views_bp = Blueprint('views_bp', __name__)


@views_bp.route('/', methods=['GET'])
def index():
    return render_template("index.html")


@views_bp.route('/profile', methods=['GET'])
def profile():
    return render_template("profile.html")


@views_bp.route('/simulate', methods=['POST'])
def simulate():
    base_model = int(request.form["baseModel"])
    waveform = int(request.form["waveform"])
    limit_bounds = bool(request.form["limitBounds"] == "1")
    q = ModelRequestObj(base_model=base_model,
                        waveform=waveform,
                        index_start=0.0,
                        index_stop=0.0,
                        increment=0.0,
                        limit_bounds=limit_bounds)

    container_obj = Container(q)
    o = json.dumps(container_obj.run(), cls=UtilsJSONEncoder)

    DataObj.drop_collection()
    database_obj = DataObj(data_string=o)
    database_obj.save()

    response_data = o
    response_status = 200
    return Response(response_data, response_status)


@views_bp.route('/data', methods=['GET'])
def data():
    if DataObj.objects:
        o = DataObj.objects.first().data_string
        response_data = o
        response_status = 200
        return Response(response_data, response_status)
    else:
        response_data = json.dumps([])
        response_status = 200
        return Response(response_data, response_status)

templates/forecastProfile.html
{% extends "layout.html" %}
{% block body %}
    <body>
    <div id="main">
        <div class="w3-container w3-center" style="color:black; font-family: serif">
            <input type="button" id="simulateForecast" value="Simulate Forecast">
            <input type="button" id="viewRawForecastData" value="View Raw Forecast Data">
            <label for="baseModel">Choose a base model:</label>
            <select name="baseModel" id="baseModel">
                <option value="C" selected="selected">C</option>
            </select>
            <label for="timeframeMultiplier">Choose a timeframe:</label>
            <select name="timeframeMultiplier" id="timeframeMultiplier">
                <option value="1" selected="selected">1 Year</option>
                <option value="5">5 Years</option>
                <option value="10">10 Years</option>
                <option value="20">20 Years</option>
                <option value="50">50 Years</option>
                <option value="100">100 Years</option>
                <option value="200">200 Years</option>

            </select>
            <br><br>
            <label for="timeframeIncrementMultiplier">Choose a timeframe increment:</label>
            <select name="timeframeIncrementMultiplier" id="timeframeIncrementMultiplier">
                <option value="0.0" selected="selected">Daily</option>
                <option value="0.01923076923">Weekly</option>
                <option value="0.0833">Monthly</option>
                <option value="0.25">Quarterly</option>
                <option value="0.5">Biannually</option>
                <option value="1.0">Annually</option>
            </select>
            <label for="displayType">Choose a display type:</label>
            <select name="displayType" id="displayType">
                <option value="0">Line and Fill</option>
                <option value="1" selected="selected">Line</option>
                <option value="2">Fill</option>
            </select>
        </div>
        <div id="forecastDisplay" class="w3-center">
            <div id="forecastObjArrayStaticVariables" style="font-family: serif" class="w3-bar w3-center"></div>
            <div id="forecastChartDivDisplay">
                <div id="forecastChartDivRows"></div>
            </div>
        </div>
    </div>
    </body>
    <script src="https://www.amcharts.com/lib/4/core.js"></script>
    <script src="https://www.amcharts.com/lib/4/charts.js"></script>
    <script src="https://www.amcharts.com/lib/4/themes/animated.js"></script>
    <script src="/static/js/forecastProfile.js"></script>
{% endblock %}

templates/index.html
{% extends "layout.html" %}
{% block body %}
<body>
    <div id="main" class="m-scene">
        <div class="scene_element scene_element--fadein">
            <h1 class="h2" style="font-family:serif; position:relative; top: 150px; text-align: center">Forecast: An Algorithm</h1>
        </div>
    </div>
</body>
{% endblock %}

templates/layout.html
<!doctype html>
<title>Forecast: An Algorithm</title>
<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.0/jquery.min.js"></script>
<div>
    <div class="w3-bar" style="font-family:serif; color:black">
        <a href="{{ url_for('views_bp.profile') }}" class="w3-bar-item w3-button w3-hover-blue">Forecast Profile</a>
    </div>
    {% for message in get_flashed_messages() %}
    {% endfor %}
    {% block body %}{% endblock %}
</div>

templates/profile.html
{% extends "layout.html" %}
{% block body %}
    <body>
    <div id="main">
        <div class="w3-container w3-center" style="color:black; font-family: serif">
            <input type="button" id="simulate" value="simulate">
            <input type="button" id="viewRawData" value="raw data">
            <label for="baseModel">Choose a base model:</label>
            <select name="baseModel" id="baseModel">
                <option value="2">Fourier Series</option>
                <option value="3">Fourier Analysis</option>
            </select>
            <label for="waveform">Choose a waveform:</label>
            <select name="waveform" id="waveform">
                <option value="0">Square</option>
                <option value="1">Triangle</option>
                <option value="2">Parabola</option>
                <option value="3">Exponential</option>
                <option value="4">Cubic</option>
                <option value="5">Cosine</option>
                <option value="6">Sine</option>
                <option value="7">Aperiodic Pulse</option>
                <option value="8">Dirac Delta - Rectangular</option>
                <option value="9">Dirac Delta - Gaussian</option>
            </select>
            <label for="limitBounds">Choose a limit bounds:</label>
            <select name="limitBounds" id="limitBounds">
                <option value=0>No</option>
                <option value=1 selected="selected">Yes</option>
            </select>
            <label for="displayType">Choose a display type:</label>
            <select name="displayType" id="displayType">
                <option value="0" selected="selected">Line and Fill</option>
                <option value="1">Line</option>
                <option value="2">Fill</option>
            </select>
        </div>
        <div id="display" class="w3-center">
            <div id="staticVariables" style="font-family: serif" class="w3-bar w3-center"></div>
            <div id="chartDivDisplay">
                <div id="chartDivRows"></div>
            </div>
        </div>
    </div>
    </body>
    <script src="https://www.amcharts.com/lib/4/core.js"></script>
    <script src="https://www.amcharts.com/lib/4/charts.js"></script>
    <script src="https://www.amcharts.com/lib/4/themes/animated.js"></script>
    <script src="/static/js/profile.js"></script>
{% endblock %}